In [57]:
import random
import numpy as np

from keras.preprocessing import sequence, text
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation, Flatten, Reshape
from keras.layers.embeddings import Embedding

from keras.layers.convolutional import Convolution1D, MaxPooling2D

import sys
import argparse
import getopt
import logging

import inspect

__author__ = 'pasquale'


def main(argv):
    n_words = 10
    embedding_dims = 5
    input_length = 3

    np.random.seed(123)
    weights = np.random.rand(10, 5)

    print(weights)

    model = Sequential()
    
    embedding_layer = Embedding(n_words, embedding_dims, input_length=input_length, weights=[weights])
    model.add(embedding_layer)
    
    print(embedding_layer.output_shape)
    
    reshape_layer = Reshape(dims=(1, input_length, embedding_dims))
    model.add(reshape_layer)
    
    print(reshape_layer.output_shape)

    pooling_layer = MaxPooling2D(pool_size=(input_length, 1))
    model.add(pooling_layer)
    
    print(pooling_layer.output_shape)
    
    #flatten_layer = Flatten()
    #model.add(flatten_layer)
    
    #print(flatten_layer.output_shape)

    model.compile(loss='binary_crossentropy', optimizer='rmsprop', class_mode='binary')
    
    input = [[0, 0, 9]]
    X = sequence.pad_sequences(input, maxlen=input_length)
    prediction = model.predict(X, batch_size=1)
    print(prediction)


if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG)
    main(sys.argv[1:])

[[ 0.69646919  0.28613933  0.22685145  0.55131477  0.71946897]
 [ 0.42310646  0.9807642   0.68482974  0.4809319   0.39211752]
 [ 0.34317802  0.72904971  0.43857224  0.0596779   0.39804426]
 [ 0.73799541  0.18249173  0.17545176  0.53155137  0.53182759]
 [ 0.63440096  0.84943179  0.72445532  0.61102351  0.72244338]
 [ 0.32295891  0.36178866  0.22826323  0.29371405  0.63097612]
 [ 0.09210494  0.43370117  0.43086276  0.4936851   0.42583029]
 [ 0.31226122  0.42635131  0.89338916  0.94416002  0.50183668]
 [ 0.62395295  0.1156184   0.31728548  0.41482621  0.86630916]
 [ 0.25045537  0.48303426  0.98555979  0.51948512  0.61289453]]
(None, 3, 5)
(None, 1, 3, 5)
(None, 1, 1, 5)
[[[[ 0.69646919  0.48303426  0.98555979  0.55131477  0.71946897]]]]
